modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/CerealCamera/Aviator-Dreams-Reloaded"
license = "GPL-3.0-only"

[[mods]]
modId = "aviator_dream"
version = "${version}"
displayName = "Aviator Dreams Reloaded"
displayURL = "https://modrinth.com/mod/aviator-dreams-reloaded"
authors = "CerealCamera"
description = "A set of additional aircraft with Create support in mind."
logoFile = "icon.png"
itemIcon = "aviator_dream:douglas_dc1"

[[dependencies.aviator_dream]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aviator_dream]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aviator_dream]]
modId = "immersive_aircraft"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "NONE"
side = "BOTH"
